### ISSUE TITLE
Rhino Widget - doesn't check is the test case already pushed to the ALM

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-widget#5]
Create one TC with X test steps 
Push it to ALM
Click push to ALM again and again 

Expected: 
Rhino should recognize this TC already exists in ALM and ask the user "TC X with the same steps already exists, are you sure you want to save duplicate TC in you ALM"?
Actual:
Each time Rhino widget will push the same TC to the ALM

**Comment by gravity-api** [comment]
Not a bug. This is by design
