### ISSUE TITLE
New version - Run automation post a console WARN message. **[Chrome driver wasn't set properly - potential irrelevant]**  

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-widget#57]
![image](https://user-images.githubusercontent.com/70174048/103820431-09c17080-5075-11eb-8ed5-f31c66b91de4.png)
{"StatusCode":500,"Message":"One or more errors occurred. (Object reference not set to an instance of an object.)","Stack":"System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)\r\n ---> System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Rhino.Api.Engine.RhinoAutomationEngine.SetPostRunResults(RhinoTestCase testCase, WebAutomation automation, OrbitResponse response)\r\n   at Rhino.Api.Engine.RhinoAutomationEngine.ExecuteSingle(RhinoTestCase testCase)\r\n   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()\r\n   at Rhino.Api.Engine.RhinoAutomationEngine.Execute(IEnumerable`1 testCases)\r\n   at Rhino.Api.RhinoConnector.OnExecuteSingle(RhinoTestCase testCase, RhinoAutomationEngine automationEngine)\r\n   at Rhino.Api.RhinoConnector.<>c__DisplayClass22_0.<OnExecute>b__0(RhinoTestCase testCase)\r\n   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)\r\n--- End of stack trace from previous location ---\r\n   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)\r\n   at System.Threading.Tasks.TaskReplicator.Replica.Execute()\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)\r\n   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)\r\n--- End of stack trace from previous location ---\r\n   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)\r\n   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)\r\n   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)\r\n   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)\r\n   at Rhino.Api.RhinoConnector.OnExecute(IEnumerable`1 testCases)\r\n   at Rhino.Api.RhinoConnector.Execute()\r\n   at Rhino.Api.Extensions.RhinoConfigurationExtensions.Execute(RhinoConfiguration configuration, IEnumerable`1 types)\r\n   at Rhino.Agent.Controllers.RhinoController.Execute() in D:\\development\\csharp\\rhino-agent\\src\\csharp\\Rhino.Agent\\Rhino.Agent\\Controllers\\RhinoController.cs:line 150\r\n   at lambda_method515(Closure , Object , Object[] )\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"}

**Comment by gravity-api** [comment]
Not relevant this is related to Jira/XRay
