### ISSUE TITLE
New version - widget post error: js/background.js:472 (anonymous function)

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-widget#58]
![image](https://user-images.githubusercontent.com/70174048/103821810-a258f000-5077-11eb-80b9-59b7aa6dfb67.png)

**Comment by YanivAroch** [comment]
![image](https://user-images.githubusercontent.com/70174048/103822141-33c86200-5078-11eb-829f-ccd2c5b79c65.png)

**Comment by gravity-api** [comment]
Cannot reproduce.
This line sends a success message to the content script (e.g., to Jira) when the automation is complete.
The error is valid if the connection has been dropped or closed.
