### ISSUE TITLE
New version - connector API error 

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-widget#59]
![image](https://user-images.githubusercontent.com/70174048/103823044-ef3dc600-5079-11eb-83cf-05a671d7ce78.png)

[rhinoapi.atlassian.net-1609969760113.log](https://github.com/savanna-projects/rhino-widget/files/5778356/rhinoapi.atlassian.net-1609969760113.log)

**Comment by gravity-api** [comment]
Related to Jira/XRay not to Rhino
