### ISSUE TITLE
New version - "Reload Test Cases" must show action indication, such as simple text "Tests reloaded" for 2 sec hard-coded

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-widget#61]
![image](https://user-images.githubusercontent.com/70174048/104136566-bfefc780-539f-11eb-9e5f-4f7d18f71c06.png)

**Comment by gravity-api** [comment]
It is shown in the console. No interactive nor complicated JS will be implemented in injected objects.
